name: Build branch

on:
  push:
    branches-ignore:
      - 1.*
      - main
    tags-ignore:
      - v1.*
      - v2.*

jobs:
  build-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v3  # Update to the latest version of checkout
    - name: 💎 Set up Ruby
      uses: ruby/setup-ruby@v1.2  # Update to the latest stable version of ruby/setup-ruby
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true  # Enable bundler cache for faster builds
    - name: 🧪 Run tests
      run: bundle exec rake
